### ISSUE TITLE
Is it a good idea to autowire a impl ?

### ISSUE THREAD

**Issue by grizzly-monkey** [divijish/ChatApplication#1]
https://github.com/divijish/ChatApplication/blob/3a4d47f31affbfcb8b8e715b2cd83a9b7aaa37c8/src/main/java/com/divij/chatapplication/controller/ChatApiController.java#L25

This will have impact when you have multiple implementations is it not ?

**Comment by divijshrivastava** [comment]
MessageService is not the implementation, it's an interface.

**Comment by grizzly-monkey** [comment]
ughh i mis read it , read only the variable name. looks good
