### ISSUE TITLE
is it a good idea to put login logic here

### ISSUE THREAD

**Issue by grizzly-monkey** [divijish/ChatApplication#2]
https://github.com/divijish/ChatApplication/blob/3a4d47f31affbfcb8b8e715b2cd83a9b7aaa37c8/src/main/java/com/divij/chatapplication/controller/ChatApiController.java#L25

Its  repo and should not decide the login logic , is it not violating Single responsibility principle. ?

**Comment by divijshrivastava** [comment]
This wasn't meant to be login logic, this is just a validation on the server side.

**Comment by grizzly-monkey** [comment]
ack..
